name: Emojis
version: 1.0.0
author: applqpak
api:
- 1.0.0
- 2.0.0
main: Emojis\Main
commands:
  emojis:
    usage: "/emojis"
    description: Emojis command.
    permission: emojis.command
permissions:
  emojis.command:
    default: true
